### ISSUE TITLE
Proper names for new doc system versus old pod/pod6

### ISSUE THREAD

**Issue by tbrowder** [Raku/RakuDoc-GAMMA#4] opened 2023-09-07 17:40 UTC
Somewhere I saw reference to 'RakuPod' and 'RakuDoc'. In the spirit of Raku, I suggest we don't use any camel-case for those terms. In addition, I suggest both should be, in general, treated the same in Raku processing **unless** the author makes the distinction inside the file by an approved ':config' keyword.

I do like the idea of saying 'Rakudoc' and 'Rakupod' are for different purposes, but I'm not sure how that will play in practice for existing code. Both '.rakudoc'and .rakupod are recognized file extensions by Raku, but they currently require a "=begin/=end pod" pair inside Raku pod to be treated as such.

My suggestions for adoption:

1. Continue to recognize '.rakupod' and '.rakudoc' as valid Raku file extensions for Rakupod-only content.
2. Continue to recognize '=begin/=end pod', but have the compiler warn of such use. (Provide a compiler option and environment variable to turn off such warnings.)
3. Recognize **"=begin/=end rakupod"** as the desired valid keyword pair for Rakupod.

I believe more discussion is needed for how to handle any distinction between uses of Rakupod.

**Comment by finanalyst** [comment] 2023-10-31 14:05
@tbrowder It is - I think - my mistake to have written 'rakupod' anywhere. I'm slightly dislexic, and sometimes mess up words and so I did use 'rakupod' in several places, where I should have said 'rakudoc'.

During a discussion when developing the new RakuDoc v2, we discussed this topic and came to the following suggestion about usage:
- the name of the markup language is: **RakuDoc** with camel case
- where the context implied a language as opposed to markup, in the past we would say *POD6*, but there was not AFAIK a consensus as to *POD6* or *Pod6*. Now it is *RakuDoc*.
- the name of a block within a RakuDoc source is: **rakudoc** and it must all be lower case because the naming convention requires builtin names to be lower case
- the legacy block name is: **pod** for backwards compatibility. However, **rakudoc** blocks may get more functionality, which will not propagate backwards to **pod** blocks. So when *pod* blocks are encountered by a renderer that is consistent with RakuDoc v2, they will be treated as *rakudoc* blocks. RakuDoc used to be compiled with the program and accessible as `$=pod`, *RakuDoc v2*  is intended to be available as a RakuAST tree. `=begin rakudoc` will be accessible as `$=pod` and there are no plans for `$=rakudoc`. However, if other semantics are given to *rakudoc* they will only be available in the RakuAST tree form, but not in the `$=pod` form. 
- the file extension is: **.rakudoc** and all file sources with *pod6* can be safely renamed to *.rakudoc*

Whilst *rakupod* was a mistake and should have been *rakudoc* (if I wrote it), is there a use case for another file extension?

**Comment by tbrowder** [comment] 2023-10-31 14:16
No, I think "rakudoc" works fine. I just wanted to be sure I'm doing the right thing.

P.S. I'm "slightly" dyslectic, too. "I feel your pain!"

**Comment by lizmat** [comment] 2023-10-31 15:44
Until recently, I would have said: I don't care that much.  Until someone pointed out to me that screen readers can better pronounce camel-cased strings, e.g. such as `#RakuLang` versus `#rakulang`.

So I would have a pretty strong preference for "RakuDoc", not only because it visually accentuates the "Doc" part, but also because screen readers will be able to pronounce "RakuDoc" better than "Rakudoc" or "rakudoc".

Now, having actually let the speech handler try these different version on my standard macOS speech synthesis, "Rakudoc" and "rakudoc" actually sound better  *sigh*

**Comment by finanalyst** [comment] 2023-11-08 16:41
@thoughtstream your thoughts on RakuDoc / Rakudoc as the name of the language?

**Comment by vrurg** [comment] 2023-11-08 17:11
I'm inclined towards RakuDoc too. Another one for it is that we must keep in mind that Raku is not widely known outside of our usual bubble. Barely many would immediately recognize "doc" in Rakudoc and thus would see the "Raku" in it.

Offtop. Thinking of people adapting it to their native langs. "Rakudozu", "Rakudoka"...

**Comment by thoughtstream** [comment] 2023-11-09 07:06
My personal preference has been for _Rakudoc_, rather than _RakuDoc_.

But I recognize that this preference is not based on any rational argument.
My older version of MacOS actually pronounces _RakuDoc_ better, and I can
see that this form also emphasizes the fundamental _Doc_-ness of the language, 
rather than merely highlighting the _Raku_ connection.

So, in the absence of any compelling counterarguments, my rational choice 
must be _RakuDoc_ for the language name, `=begin rakudoc`...`=end rakudoc`
for the block delimiters, and `.rakudoc` for the extension.

I do, however, like the idea of being liberal in what we accept and strict in what we emit.
So, whatever we decide the official name should be, we should ensure that the specification
uses ***only*** that official form, but we should also include language that defines our culture
of tolerance. Specifically: that anyone who accidentally or deliberately uses other form 
will never be mocked, berated or ostracized for doing so.

**Comment by finanalyst** [comment] 2023-11-13 15:21
Draft changed to accommodate these views. Closing as resolved

**Closed by finanalyst** 2023-11-13 15:21 UTC

**Comment by thoughtstream** [comment] 2024-05-22 23:37
I've tweaked the commit quite heavily this time 
to (I hope!) make our intentions more explicit
and make the behaviour clearer to non-expert readers

I also noticed some regressions on _"RakuDoc vs Rakudoc"_ issue, 
and have corrected them.

Also, there is no hyphen in the word "override". ;-)

My suggestions are as follows:
```diff
--- PR28.rakudoc	2024-05-23 08:48:27.000000000 +1000
+++ PR28_tweaks.rakudoc	2024-05-23 09:33:17.000000000 +1000
@@ -114,9 +114,9 @@
 
 =head1 Two use cases for RakuDoc
 
-Rakudoc can be thought of as having components that are closely connected to a program or module
-that is being documented (D<code-oriented Rakudoc>), and components that can be used for text-oriented documents, such as the source
-for a webpage or a book (D<text-oriented Rakudoc>).
+RakuDoc can be thought of as having components that are closely connected to a program or module
+that is being documented (D<code-oriented RakuDoc>), and components that can be used for text-oriented documents, such as the source
+for a webpage or a book (D<text-oriented RakuDoc>).
 
 Code-oriented RakuDoc is expected to be "consumed" by users in an editor or Integrated Design Environment (IDE),
 while text-oriented RakuDoc is consumed in some rendered version,
@@ -152,7 +152,7 @@
 provided for the class within the same source file. By passing the source through a renderer, a
 documentation file (e.g. a README.md file for a github repo) can be generated.
 
-This document describes the minimum version of Rakudoc that a renderer or editor must recognise along with
+This document describes the minimum version of RakuDoc that a renderer or editor must recognise along with
 some expected rendering behaviors for text-oriented renderers. I<"Expected behaviors"> means that a renderer
 should approximate the behavior as far as possible given the limitations of the output format, and that the
 approximation should be a reasonable interpretation of the standard described here.
@@ -508,32 +508,49 @@
 =end code
 
 Within the same block scope, eg., between C<=begin section> and C<=end section> instructions,
-C<=config> directives are cumulative and define the default behaviour of some block type. When metadata
-are specified for an instance of that block type, those options over-ride the default set by C<=config> blocks.
-For example,
+one or more C<=config> directives can be specified to define the default behaviour of specific block types.
+Successive C<=config> directives within the same scope are cumulative in effect.
+Because C<=config> directives specify I<default> behaviours, whenever a particular kind of metadata
+is explicitly specified for an instance of that block type, that option overrides the default set by any active C<=config> blocks.
+For example:
 =begin code :lang<RakuDoc>
     =config code :allow< B C I >
+    # The default metadata for any code block is now:  :allow< B C I >
+
     =begin code
        # In this paragraph B<this phrase will be shown as basis (possibly in bold font)>
        # and I<this will be shown as important (possibly italics)>.
-       # But R<markup> will be shown verbatim.
-       # The language for the block is the generic default of B<Raku>.
+       # But other markup such as R<placeholder> and K<input> will be shown verbatim.
+       #
+       # Because no :lang<> option was configured, the language for the block
+       # is the generic default:  :lang<Raku>
     =end code
+
     =config code :lang<RakuDoc>
+    # The default metadata for any code block is now:  :allow< B C I > :lang<RakuDoc>
+
     =begin code :allow< R K >
-       # Here B<markup> and I<markup> are shown verbatim, while R<this will be shown as a replacement text>.
-       # The language for the block is B<RakuDoc>.
+       # Here the explicit :allow on the block overrides the default :allow from the =config
+       # so B<markup> and I<markup> are shown verbatim, while R<this will be shown as a replacement text>.
+       #
+       # There is no explicit :lang on the code block,
+       # so the language for the block is the configured default:  :lang<RakuDoc>
     =end code
-    =code sub B<a-basic-subroutine> ( I<$param> ) { 'the markup codes here will be rendered by default again' }
+
+    =code # Now we're back to B<basic> and I<important>, but not R<placeholder> or K<input>
 
     =begin section
-    =config code :allow< R K >
-    =begin code :lang<JavaScript>
-        // Now format codes R K are activated by default,
-        // but by default B<> C<> I<> markup will be shown verbatim
-        // meanwhile the language has been explicitly set to Javascript
-        // (important if syntax highlighting is turned on)
-    =end code
+        =config code :allow< R K >
+        # The default metadata for any code block is now:  :allow< R K > :lang<RakuDoc>
+
+        =begin code :lang<JavaScript>
+            // The format codes R and K are activated by default,
+            // but B<> C<> I<> markup will be shown verbatim
+            //
+            // The language has been explicitly set to Javascript
+            // (important if syntax highlighting is turned on),
+            // so the default language (RakuDoc) is overridden
+        =end code
     =end section
 =end code
 
@@ -762,12 +779,12 @@
 When C<$=data> itself is stringified, it returns the concatenation of all
 the unkeyed C<=data> blocks the parser has seen.
 
-C<=data> blocks are never rendered by the text-oriented Rakudoc renderers.
+C<=data> blocks are never rendered by the text-oriented RakuDoc renderers.
 
 =head1 Text-oriented RakuDoc
 
-The Rakudoc instructions in this section are primarily intended for text-oriented rendering.
-However, text-oriented and code-oriented Rakudoc can be freely intermixed with Raku
+The RakuDoc instructions in this section are primarily intended for text-oriented rendering.
+However, text-oriented and code-oriented RakuDoc can be freely intermixed with Raku
 code in a single file; this may help to create code that is well-documented.
 
 When a Raku compiler parses a file, line contents are expected to be Raku code (ambient text).
@@ -1326,7 +1343,7 @@
 may have a different bullet. A compliant renderer will define a I<default> bullet for at least the first four
 levels within a nested list, with the bulleting strategy for other levels being up to the renderer.
 
-The default bullet can be over-ridden with a custom bullet for any C<=item>R<N>, for example
+The default bullet can be overridden with a custom bullet for any C<=item>R<N>, for example
 =begin code :lang<RakuDoc> :allow<B>
 The project originally consisted of five phases, of which
 two are already complete and two have been abandoned:
@@ -1654,7 +1671,7 @@
 C<:caption> option and included in the L<Table of Contents|#Table of Contents and Index>.
 
 A I<procedural> table may only be specified in the I<delimited> form.
-As will become clear below, I<procedural semantics> are assumed if the next Rakudoc instruction
+As will become clear below, I<procedural semantics> are assumed if the next RakuDoc instruction
 after a C<=begin table> is one of C<=row>, C<=column>, or C<=cell>.
 
 =head3 Visual description of simple tables
@@ -2632,7 +2649,7 @@
 Each block creates a virtual margin (at the column before its leading C<=>)
 and that virtual margin extends B<I<only>> to the end of the block (I<i.e.> B<not> to the start
 of the next named block). Thus:
-=begin code :lang<Rakudoc>
+=begin code :lang<RakuDoc>
 ┊=begin rakudoc
 ┊This is an implicit =para block
 ┊
@@ -2667,7 +2684,7 @@
 =end code
 
 Which means that:
-=begin code :lang<Rakudoc>
+=begin code :lang<RakuDoc>
 =begin rakudoc
     =for Podcast
         this is not code
@@ -2679,7 +2696,7 @@
 of its containing C<=begin rakudoc>/C<=end rakudoc> block, so it must be code.
 
 Whereas:
-=begin code :lang<Rakudoc>
+=begin code :lang<RakuDoc>
     =begin rakudoc
     =for Podcast
         this is not code
@@ -2693,7 +2710,7 @@
 Care must be taken with I<abbreviated> and I<extended> blocks where the block ends at the
 next blank line.
 
-=begin code :lang<Rakudoc>
+=begin code :lang<RakuDoc>
     =begin rakudoc
     This is an ordinary paragraph
 
@@ -2723,7 +2740,7 @@
 (and reverts at that point to the virtual margin of the surrounding block, if any).
 
 Which means:
-=begin code :lang<Rakudoc>
+=begin code :lang<RakuDoc>
     =begin rakudoc
     This is an ordinary paragraph
 
@@ -2755,7 +2772,7 @@
 an implicit paragraph block (i.e. not an implicit code block),
 you'd write it:
 
-=begin code :lang<Rakudoc>
+=begin code :lang<RakuDoc>
     =begin rakudoc
     This is an ordinary paragraph
 
@@ -2979,10 +2996,14 @@
 The table contains suggested HTML and Markdown equivalents; a renderer may
 choose other representations.
 
-This syntax clearly makes it impossible to associate metadata options with formatting codes explicitly.
-It is possible to do this via a C<=config> directive. For example, C< C<> > markup by default does not allow for
-embedded format codes to be rendered, but an author might want C< B<> > to be allowed, as shown in the
-L<syntax section|#Directive syntax>.
+This syntax does not provide a mechanism to associate metadata options with formatting codes explicitly.
+It is, however, possible to do this via a C<=config> directive. For example, C< C<> > markup by default does not allow for
+embedded format codes to be rendered, but an author might want C< B<> > to be allowed. This can be
+achieved with:
+
+=code =config C :allow<B>
+
+This mechanism is explained further in the L<syntax section|#Directive syntax>.
 
 =head2 Instructions with side effects
 
@@ -3013,8 +3034,8 @@
 =item C<https://> or C<http://> The renderer may style the label and cause a jump in
 a networked environment, as is normal for HTML documents.
 
-=item C<rakudoc:> A reference to a Rakudoc source, which might be in a Raku module
-or a Rakudoc file.
+=item C<rakudoc:> A reference to a RakuDoc source, which might be in a Raku module
+or a RakuDoc file.
 
 =item C<mailto:> An email address. Typically, activating this type of link invokes a mailer.
 
@@ -3468,7 +3489,7 @@
 
 The default behaviors of both C<V<>> and C<C<>> can be changed using a C<=config>
 directive, e.g.,
-=begin code :lang<Rakudoc>
+=begin code :lang<RakuDoc>
 =config C :allow< B I U >
 =config V :allow< N L X >
 =end code
@@ -3537,7 +3558,7 @@
 the first string will be made available in the same way as the C<D<>> markup instruction. It is also recommended that the first string
 is used by the renderer to identify the functionality being provided.
 
-For example, suppose a Rakudoc document is used to create part of a website in which a button is to be styled
+For example, suppose a RakuDoc document is used to create part of a website in which a button is to be styled
 that accesses the API of a payment service (e.g. 'PayMe'). A developer can then create some functionality according
 to the rules of a RakuDoc renderer, and present it to the service point. In an HTML document, this might be coded
 as a C< <button class="PayMeApp" data-token="vendor-id" data-price="$0.99"> > with a specific class and structure.
```
