### ISSUE TITLE
Clarify the status of blank lines before and after blocks

### ISSUE THREAD

**Issue by vrurg** [Raku/RakuDoc-GAMMA#7] opened 2023-11-01 13:49 UTC
In a way, this is a followup to rakudo/rakudo#5442. 

The current RakuAST implementation treats empty lines before and after blocks as insignificant delimiters, no exceptions made. Up to my understanding, this is to follow guidelines in [this synopsis](https://github.com/Raku/old-design-docs/blob/63e44c36351887f1eb76500d7102f0db44848d27/S26-documentation.pod#L172). This approach results in LTA behavior with regard to the blank lines when AST of an existing document is deparsed.

My understanding is that anything within any RakuDoc block is part of the document where formatting may play role to the document writer. Blank lines are no exception as, for example:

```
=begin rakudoc

=begin item
I1
=end item
=begin item 
I2
=end item

=begin item
Not sure yet if this one is to be included.
=end item
=end rakudoc
```

Visual separation can be insignificant for the output, but it is helpful for the writer themselves.

I think the statement about blank lines must only apply to the outers of a rakudoc. I.e. it must play role for something like:

```raku
=item Argument 1 is...

=item Argument 2 is ...

method foo($arg1, $arg2) {...}
```

In the above example both item texts would have exactly one trailing newline.

**Comment by finanalyst** [comment] 2023-11-02 23:09
@vrurg In RakuDoc the situation is not the same as RakuAST.

A block is defined as terminating with a blank line or a new block. So, 
```
=item this is the first item, short on one line
=item this is the second item, no need for a blank line above since on one line
=item this is the third item,
but the text extends to another line

=item this is the fourth item, but it needs to be distinguished from the previous one by a 
blank line because the third item ran over lines.

This text is now a para block and is not an item
```

**Comment by vrurg** [comment] 2023-11-03 13:44
BTW, yes, your example touches another nuance.

Is the blank line part of the abbreviated block above it? I mean, when rendered it is obviously will be ignored. But how do I know, while traversing RakuAST, if the block had that trailing blank line(s) or not? Basically, it winds down to how we treat the following:

```
=item I1
=item I2

=item I3

Para
```

Would that be:

```
=begin item
I1
=end item
=begin item
I2
=end item
=begin item
I3
=end item
```

Or, as I'd expect it:

```
=begin item
I1
=end item
=begin item
I2

=end item
=begin item
I3
=end item

Para
```

Though it's still questionable where the blank line before the paragraph belongs to.

Apart of that, my example is about `=begin`. What about the spacing before `=begin` and after `=end`? My point is that it must be part of the surrounding text. E.g. the blanks between an `=end` and the following `=begin` become a paragraph containing these blanks as-is.

The overall point is to let `DEPARSE` produce the same output as the originally parsed document. Exactly for the reason that it is a _document_ where content matters.

**Comment by finanalyst** [comment] 2023-11-05 21:08
@vrurg @lizmat @thoughtstream  Some of this discussion is beyond me at the moment in that it relates to the interaction of RakuAST and RakuDoc.
Some comments (and attach 'I think' to all of them)
- it is very important to distinguish between a 'block' in the ambient (that is in a Raku program) and a 'block' in RakuDoc. By doing so, the rules for a 'block' may differ.
- In RakuDoc, an explicit blank line (or lines) may terminate a block, but is not a part of the *content* of the block.
  - In this respect the first & terminating blank line is equivalent to a `=end xxx` line. The terminator is not included in the *content*
- In order to ensure that blank lines can be included as *content*, there are special verbatim blocks, such as `code` and `output` that when delimited with `=begin / =end` preserve whitespace both vertical and horizontal.
- In the example given above
```
=item I2

=item I3
```
would only have `I2` as the content of the block, so it would be equivalent to 
```
=begin item
I2
=end item
```
If you want to have explicit vertical whitespace in the item 2, you would need
```
=begin item
=begin code
I2

=end code
=end item
```

From the issue statement here and the other one cited above, the ambiguity may arise when RakuDoc blocks are mixed together with ambient Raku. If this is the case, then a solution may be to **require** all RakuDoc statements to be enclosed within a `=begin rakudoc / =end rakudoc` terminators (other than perhaps `=comment`) and for whatever is within them to be considered a Raku block with the leading and trailing blank lines as defined by RakuAST.

**Comment by vrurg** [comment] 2023-11-06 15:51
> it relates to the interaction of RakuAST and RakuDoc.

I'd say it relates to any RakuDoc parsing engine, not RakuDoc alone.

> * it is very important to distinguish between a 'block' in the ambient (that is in a Raku program) and a 'block' in RakuDoc. By doing so, the rules for a 'block' may differ.

That's part of my expectations.

> * In order to ensure that blank lines can be included as _content_, there are special verbatim blocks, such as `code` and `output` that when delimited with `=begin / =end` preserve whitespace both vertical and horizontal.

I didn't consider this aspect previously, BTW. To me plain `=item I1\n\n\n` would render into just _I1_ implicitly. The question of preserving the newlines remains, but I'll be back to it later. For the moment, I don't like the idea of using `code` or `output` because these are likely to be formatted, with font and background differring from the surrounding text.

Perhaps it would make more sense to have `:verbatim` with `para`:

```
=begin para :verbatim
I1

=end para
```

> * In RakuDoc, an explicit blank line (or lines) may terminate a block, but is not a part of the _content_ of the block.

This is also apparent. The question is what representation specific cases would have within a parser. Not that RakuDoc spec must regulate it, but concrete wording would let avoid discrepancies in treating the original document.

Back to the examples.

```
=item I1


=item I2
```

When it comes to internal representation, would it be:

- item<I1>
- "\n\n"
- item<I2>

Or:

- item<I1>
- item<I2>

Though my preferences still goes to

- item<I1\n>
- item<I2>

The point in doing so is that it'd be up to a renderer to decide how to treat the trailing newlines. Most would ignore them (except if the idea about `:verbatim` makes it through).

BTW, there are also cases of:

```
=item the last

Text goes here
```

But I think it would still has to be `item<the last\n\n` because the blank here is more of a terminator than part of the text.

When it comes to `=begin`, then there is very little is to be discussed about the separating newlines:

```
=begin item
I1
=end item


=begin item
I2
=end item
```

This is:

- item<I1>
- "\n\n"
- item<I2>

Then, again, a rendered may or may not pay respect to the blanks. But to whatever tool these blanks may matter – they wouldn't be lost after parsing. 


And getting a little bit back, as to what to do about:

```
=begin item
I1

=end item
```

I'd expect this also to be considered as `item<I1\n\n>`. Then, again, a renderer is likely to ignore these, but any other tool would know about them and use them for whatever purpose it has.

To wind down a bit:

We must remember that aside of the renderers there are other tools to come. For them elements of the original document we consider irrelevant for the representation may have different meaning for processing the doc in the context of the task they're solving. Apparently, they could develop their own parser in order to have these bits available. But why'd they need it for if there is RakuAST around? By taking into account that it is based on the spec, all we need is to make the spec clear about such edge cases.

**Comment by finanalyst** [comment] 2023-11-07 14:16
@vrurg The issue you are concerned about seems to be the way RakuAST pre-processes the RakuDoc source, and the "entropy" (more later, because it is important for another reason).

RakuDoc does not care about whitespace as content, unless directed to using a Verbatim block or `S< ... >` markup, which preserves horizontal white-space inline.

You suggested that the specification be amended. In the section on 'Block syntax' suppose we add text at the end of the section as follows:
```
Where an extended or abbreviated block forms uses a blank line as the block terminator, the blank line is not included as part of the content of the block. All subsequent whitespace, whether horizontal or vertical (spaces, tabs, new lines), is ignored. Note that horizontal and vertical whitespace can be included inside delimited blocks, as described below.
```
Is that acceptible?

Verbatim blocks. Using a `:verbatim` metadata option on a paragraph is not a good idea. The problem is that RakuAST would need to look for metadata and obey them. An aspect of the design of RakuDoc was to clearly distinguish between the responsibility of the compiler and the renderer. The compiler handles blocks, the renderer handles metadata options. 

Paragraphs by definition squash all whitespace. 

A code (verbatim) block explicitly allows for white space to be preserved. 

It would be better for a code or verbatim block to be given a metadata option to remove styling. In fact, we have got `:syntax-highlighting` to turn on syntax highlighting in combination with `:lang`. So not turning on syntax-highlighting will render a code block with no other marking. 

## Entropy
Currently RakuAST discards all comments and vertical whitespace, delivering only the expected contents. Indeed the renderer is required to handle the horizontal whitespace itself.

Thus RakuAST increases entropy.

The problem is that when a document is DEPARSED, the discarded portions are needed. For example,
```
my $a = '1'; # this is a comment
```
yields a RakuAST structure without the comment.

In order to create a syntax highlighter that works directly from DEPARSE, the comments need to exist somewhere. 

I wonder whether that if we want extra horizontal whitespace, this is included in the same way comments are.

**Comment by vrurg** [comment] 2023-11-07 15:48
> Is that acceptible?

Looks good to me. Hopefully, the part about "inside delimited blocks" covers the `=begin rakudoc` block too. It should. 

> Verbatim blocks. Using a `:verbatim` metadata option on a paragraph is not a good idea. The problem is that RakuAST would need to look for metadata and obey them.

This is not what I meant. If memory serves me well (and it doesn't because I needed to google it out first ;) ), my interpretation of `verbatim` vs. `code` or `pre` comes from LaTex.

The problem of interpreting `verbatim` as `code` is the way it would be rendered. It is not always that where one wants 1-to-1 treatment for a block of text they also want it to be in a fixed font with likely different background. Currently there is nothing in between "we don't care about text structure" and "it is a code block".

A use for such blocks would be, for example, inserting some lengthy poetry into text where line breaks and spaces between stanzas do matter. Apparently, one can use explicit line break code (which we don't have), but it'd be tedious. Instead:

```
=begin para :verbatim
How doth the little crocodile
Improve his shining tail,
And pour the waters of the Nile
On every golden scale!

How cheerfully he seems to grin,
How neatly spreads his claws,
And welcomes little fishes in,
With gently smiling jaws!
=end para
```

BTW, `V<>`, [as documented](https://docs.raku.org/language/pod#Verbatim_text), seemingly does almost that.

**Comment by finanalyst** [comment] 2023-11-08 16:27
@vrurg There are always going to be special needs. For this reason, RakuDoc v2 expressly allows for Custom blocks. It is then for the custom block to handle the 'contents' (all the text between `=begin` and `=end`, including whitespace, horizontal and vertical).

**Comment by finanalyst** [comment] 2023-11-13 15:22
closing as resolved

**Closed** 2023-11-13 15:22 UTC
